<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HTURD8O" failures="0" tests="1" name="TestCase.FirstTest$Base_Class" time="0.038" errors="1" timestamp="2025-01-07T12:53:09 IST" skipped="0">
  <testcase classname="TestCase.FirstTest$Base_Class" name="setup" time="0.038">
    <error message="Appium HTTP server has started and is listening although we were unable to get an OK response from http://127.0.0.1:4723/status. Make sure both the client and the server use the same base path &#039;/&#039; and check the server log for possible error messages occurrences.
Response status code: 404
Response payload: {&quot;status&quot;:9,&quot;value&quot;:{&quot;error&quot;:&quot;unknown command&quot;,&quot;message&quot;:&quot;The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource&quot;,&quot;stacktrace&quot;:&quot;&quot;}}
Node.js executable path: C:\Program Files\nodejs\node.exe
Arguments: [C:\Users\Admin\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1]" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: Appium HTTP server has started and is listening although we were unable to get an OK response from http://127.0.0.1:4723/status. Make sure both the client and the server use the same base path '/' and check the server log for possible error messages occurrences.
Response status code: 404
Response payload: {"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}
Node.js executable path: C:\Program Files\nodejs\node.exe
Arguments: [C:\Users\Admin\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1]
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)
at TestCase.FirstTest$Base_Class.setup(FirstTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionError: ConnectionError
at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.checkResponse(AppiumServerAvailabilityChecker.java:91)
at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:62)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)
... 27 more
]]>
    </error>
  </testcase> <!-- setup -->
</testsuite> <!-- TestCase.FirstTest$Base_Class -->
